config/routes.rb
# frozen_string_literal: true

# == Route Map
#

Rails.application.routes.draw do
  resources :incoterms, only: %i[index]
  resources :shipments do
    member do
      get :itenary
      get :pdf
    end
  end

  resources :audits, only: %i[destroy]
  resources :quotes do
    member do
      get :pdf
    end
  end
  resources :locations, except: %i[show]
  # resources :customers
  resources :dashboard, only: %i[index]
  get 'dashboard/index'
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :shipments do
        collection do
          post :verify
          get :send_pdf_email
          get :preview_pdf
        end
      end
      resources :quotes, only: %i[create]
      resources :enquiries, only: %i[create]
      resources :incoterms, only: %i[index]
    end
  end

  # Defines the root path route ("/")
  root to: 'shipments#index'
end

app/models/quote.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: quotes
#
#  id                 :bigint           not null, primary key
#  frieght_type       :integer          default("air"), not null
#  height             :decimal(5, 2)    not null
#  is_deleted         :boolean          default(FALSE), not null
#  length             :decimal(5, 2)    not null
#  message            :text(65535)      not null
#  status             :integer          default("pending")
#  total_gross_weight :decimal(5, 2)    not null
#  width              :decimal(5, 2)    not null
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  departure_id       :bigint           not null
#  destination_id     :bigint           not null
#  incoterm_id        :bigint           not null
#  quoter_id          :bigint           not null
#
# Indexes
#
#  index_quotes_on_departure_id    (departure_id)
#  index_quotes_on_destination_id  (destination_id)
#  index_quotes_on_incoterm_id     (incoterm_id)
#  index_quotes_on_quoter_id       (quoter_id)
#
# Foreign Keys
#
#  fk_rails_...  (departure_id => locations.id)
#  fk_rails_...  (destination_id => locations.id)
#  fk_rails_...  (quoter_id => customers.id)
#
class Quote < ApplicationRecord
  include DestroyRecord
  audited only: %i[status]

  enum frieght_type: { air: 1, land: 2, sea: 3, rails: 4 }
  enum status: { pending: 1, processing: 2, approved: 3, rejected: 4, expired: 5, cancelled: 6, booked: 7,
                 in_transit: 8, delivered: 9, problem: 10 }

  belongs_to :departure, class_name: 'Location', optional: false
  accepts_nested_attributes_for :departure

  belongs_to :destination, class_name: 'Location', optional: false
  accepts_nested_attributes_for :destination

  belongs_to :incoterm

  belongs_to :quoter, optional: false
  accepts_nested_attributes_for :quoter

  validates :frieght_type, :total_gross_weight, :height, :width, :length, :message, presence: true
  validates :total_gross_weight, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/api/v1/quotes_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class QuotesController < ApiController
      # POST : /api/v1/{quotes}
      def create
        service = CreateQuoteService.new(params: quote_params)
        service.perform
        @quote = service.quote

        if service.errors.blank?
          QuoteMailer.with(quote: @quote).new_quote.deliver_later
          render_success('success', @quote, QuoteSerializer)
        else
          render_error(@quote.errors.full_messages)
        end
      end

      private

      def quote_params
        params.permit(:frieght_type, :height, :length, :width, :message, :status, :total_gross_weight, :incoterm_id, :departure, :destination, :name, :email, :phone, departure_attributes: %i[city country], destination_attributes: %i[city country], quoter_attributes: %i[name email phone])

        # params.require(:quote).permit(:frieght_type, :height, :length, :width, :message, :status, :total_gross_weight, :incoterm_id, :departure, :destination, :name, :email, :phone, departure_attributes: %i[city country], destination_attributes: %i[city country], quoter_attributes: %i[name email phone])
      end
    end
  end
end

app/controllers/quotes_controller.rb
# frozen_string_literal: true

class QuotesController < ApplicationController
  before_action :set_quote, only: %i[show edit update destroy pdf]

  # GET /quotes or /quotes.json
  def index
    @quotes = Quote.includes(:departure, :destination, :incoterm, :quoter).order(created_at: :desc).all
  end

  # GET /quotes/1 or /quotes/1.json
  def show; end

  # GET /quotes/new
  def new
    @quote = Quote.new
    @quote.build_quoter
    @quote.build_departure
    @quote.build_destination
  end

  # GET /quotes/1/edit
  def edit; end

  # GET /shipments/1/pdf
  def pdf
    render_pdf
  end

  # POST /quotes or /quotes.json
  def create
    service = CreateQuoteService.new(params: quote_params)
    service.perform

    @quote = service.quote

    respond_to do |format|
      if service.errors.blank?
        format.html { redirect_to new_quote_url, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1 or /quotes/1.json
  def update
    service = UpdateQuoteService.new(quote: @quote, params: quote_params)
    service.perform

    @quote = service.quote

    respond_to do |format|
      if service.errors.blank?
        format.html { redirect_to quote_url(@quote), notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1 or /quotes/1.json
  def destroy
    @quote.destroy

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.remove("#{helpers.dom_id(@quote)}_row")
      end
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_quote
    @quote = Quote.includes(:departure, :destination, :incoterm, :quoter).find(params[:id])
  end

  def quote_params
    params.require(:quote).permit(:frieght_type, :height, :length, :width, :message, :status, :total_gross_weight, :incoterm_id, departure_attributes: %i[city country], destination_attributes: %i[city country], quoter_attributes: %i[name email phone])
  end

  def render_pdf
    render(template: 'quotes/pdf', pdf: 'invoice', page_size: 'A4', margin: { bottom: 22 }, footer: { html: { template: 'pdf_document_footer' } })
  end
end

app/helpers/quotes_helper.rb
# frozen_string_literal: true

module QuotesHelper
end

app/views/quotes/_form.html.erb
<%= form_with(model: quote, id: "new_quote_form",  class: "w-full max-w-xl mx-auto") do |form| %>

  <% if quote.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mb-3">
      <h2><%= pluralize(quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
        <% quote.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <form>
    <div class="grid md:grid-cols-2 md:gap-6">
      <div class="relative z-0 w-full mb-5 group">
          <label for="status" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Status</label>

          <%= form.select :status, Quote.statuses.collect { |q| [ q[0].capitalize.gsub("_", " "), q[0] ] }, { include_blank: "Choose a new status" }, { class: "block py-2.5 px-0 w-full text-sm bg-transparent border-0 border-b-2 border-gray-200 appearance-none dark:text-gray-400 dark:border-gray-700 focus:outline-none focus:ring-0 focus:border-gray-200 peer" } %>
      </div>
      <div class="relative z-0 w-full mb-5 group">
          <%= form.number_field :total_gross_weight, min: 0, step: 0.1, class: "block py-2.5 px-0 w-full text-sm bg-transparent border-0 border-b-2 border-gray-200 appearance-none dark:text-gray-400 dark:border-gray-700 focus:outline-none focus:ring-0 focus:border-gray-200 peer", required: true, placeholder: '' %>

          <label for="total_gross_weight" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Total gross weight (kg)</label>
      </div>
    </div>

    <%= form.fields_for :departure do |departure_form| %>

      <p class="text-xs font-medium mb-2 mt-2">Departure</p>

      <div class="grid md:grid-cols-2 md:gap-6">
        <div class="relative z-0 w-full mb-5 group">
            <%= departure_form.text_field :city, class: 'block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-gray-400 dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer', placeholder: '', autocomplete: 'off', required: true %>

            <label for="city" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Name of city</label>
        </div>

        <div class="relative z-0 w-full mb-5 group">
            <%= departure_form.text_field :country, class: 'block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-gray-400 dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer', placeholder: '', autocomplete: 'off', required: false %>

            <label for="country" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">country</label>
        </div>
      </div>

    <% end %>

    <%= form.fields_for :destination do |destination_form| %>

      <p class="text-xs font-medium mb-2 mt-2">Destination</p>

      <div class="grid md:grid-cols-2 md:gap-6">
        <div class="relative z-0 w-full mb-5 group">
            <%= destination_form.text_field :city, class: 'block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-gray-400 dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer', placeholder: '', autocomplete: 'off', required: true %>

            <label for="city" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Name of city</label>
        </div>

        <div class="relative z-0 w-full mb-5 group">
            <%= destination_form.text_field :country, class: 'block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-gray-400 dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer', placeholder: '', autocomplete: 'off', required: false %>

            <label for="country" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">country</label>
        </div>
      </div>

    <% end %>

    <div class="grid md:grid-cols-2 md:gap-6">
      <div class="relative z-0 w-full mb-5 group">
          <label for="frieght_type" class="sr-only">Frieght type</label>

          <%= form.select :frieght_type, Quote.frieght_types.collect { |q| [ q[0].capitalize, q[0] ] }, { include_blank: "Choose an frieght type" }, { class: "block py-2.5 px-0 w-full text-sm bg-transparent border-0 border-b-2 border-gray-200 appearance-none dark:text-gray-400 dark:border-gray-700 focus:outline-none focus:ring-0 focus:border-gray-200 peer" } %>
      </div>
      <div class="relative z-0 w-full mb-5 group">
          <label for="incoterms" class="sr-only">Incoterms</label>

          <%= form.select :incoterm_id, Incoterm.all.collect { |q| [ q.abbr, q.id ] }, { include_blank: "Choose an incoterm" }, { class: "block py-2.5 px-0 w-full text-sm bg-transparent border-0 border-b-2 border-gray-200 appearance-none dark:text-gray-400 dark:border-gray-700 focus:outline-none focus:ring-0 focus:border-gray-200 peer" } %>
      </div>
    </div>

    <p class="text-xs font-medium mb-5 mt-2">Dimensions</p>

    <div class="grid md:grid-cols-2 md:gap-6">
      <div class="relative z-0 w-full mb-5 group">
          <%= form.number_field :height, min: 0, step: 0.1, class: "block py-2.5 px-0 w-full text-sm bg-transparent border-0 border-b-2 border-gray-200 appearance-none dark:text-gray-400 dark:border-gray-700 focus:outline-none focus:ring-0 focus:border-gray-200 peer", required: true, placeholder: '' %>

          <label for="height" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Height (ft)</label>
      </div>
      <div class="relative z-0 w-full mb-5 group">
          <%= form.number_field :length, min: 0, step: 0.1, class: "block py-2.5 px-0 w-full text-sm bg-transparent border-0 border-b-2 border-gray-200 appearance-none dark:text-gray-400 dark:border-gray-700 focus:outline-none focus:ring-0 focus:border-gray-200 peer", required: true, placeholder: '' %>

          <label for="length" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Length (ft)</label>
      </div>
    </div>

    <div class="grid md:grid-cols-2 md:gap-6">
      <div class="relative z-0 w-full mb-5 group">
          <%= form.number_field :width, min: 0, step: 0.1, class: "block py-2.5 px-0 w-full text-sm bg-transparent border-0 border-b-2 border-gray-200 appearance-none dark:text-gray-400 dark:border-gray-700 focus:outline-none focus:ring-0 focus:border-gray-200 peer", required: true, placeholder: '' %>

          <label for="width" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Width (ft)</label>
      </div>
    </div>

    <p class="text-xs font-medium mb-5 mt-2">Personal Details</p>

    <%= form.fields_for :quoter do |quoter_form| %>

        <div class="grid md:grid-cols-1 md:gap-6">
          <div class="relative z-0 w-full mb-5 group">
              <%= quoter_form.text_field :name, class: 'block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-gray-400 dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer', placeholder: '', autocomplete: 'off', required: false %>

              <label for="first_name" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Full name</label>
          </div>
        </div>

        <div class="grid md:grid-cols-2 md:gap-6">
          <div class="relative z-0 w-full mb-5 group">
              <%= quoter_form.text_field :email, class: 'block py-2.5 px-0 w-full text-sm bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-gray-400 dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer', placeholder: '', autocomplete: 'off', required: false %>

              <label for="email" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Email</label>
          </div>
          <div class="relative z-0 w-full mb-5 group">
              <%= quoter_form.telephone_field :phone, class: 'block py-2.5 px-0 w-full text-sm bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-gray-400 dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer', placeholder: '', autocomplete: 'off', required: false %>

              <label for="phone" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Phone number</label>
          </div>
        </div>

    <% end %>

    <div class="relative z-0 w-full mb-5 group">
        <%= form.text_area :message, cols: 20, rows: 6, class: "block p-2.5 w-full text-sm bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", required: true, placeholder: "Write your message here..." %>
    </div>

    <%= form.submit "Save", class: 'text-white bg-blue-700 hover:bg-blue-800 rounded-lg cursor-pointer focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium w-full sm:w-auto px-4 py-2 my-3 text-sm text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800' %>

    <%= link_to "Back to quotes", quotes_path, class: "rounded-lg font-medium w-full text-sm sm:w-auto px-4 py-2 my-3 text-center bg-gray-100 inline-block font-medium" %>

  </form>

<% end %>

app/views/quotes/_quote.html.erb
<tr id="<%= "#{dom_id(quote)}_row" %>", class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
  <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
      <%= quote.departure.city %>
  </th>
  <td class="px-6 py-4">
      <%= quote.destination.city %>
  </td>
  <td class="px-6 py-4">
      <%= quote.total_gross_weight %>
  </td>
  <td class="px-6 py-4">
      <%= quote.frieght_type.capitalize %>
  </td>
  <td class="px-6 py-4">
      <%= quote.status&.capitalize %>
  </td>
  <td class="px-6 py-4">
      <%= link_to "Show", quote_path(quote), class: "font-medium text-blue-600 dark:text-blue-500 hover:underline" %>
      <%= link_to "Destroy", quote, data: { turbo_confirm: "Are you sure?", turbo_method: :delete }, class: "font-medium text-red-600 dark:text-red-500 hover:underline" %>
  </td>
</tr>

app/views/quotes/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-2xl">Editing quote</h1>

  <hr class="mt-3 mb-7" />

  <%= render "form", quote: @quote %>
</div>

app/views/quotes/index.html.erb
<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-2xl">Quotes</h1>
    <%= link_to "New quote", new_quote_path, class: "rounded py-2 px-5 bg-blue-600 text-white text-sm block font-medium" %>
  </div>

  <hr class="mt-3 mb-7" />

  <div id="quotes" class="min-w-full">
    <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
      <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
          <tr>
            <th scope="col" class="px-6 py-3">
                Departure
            </th>
            <th scope="col" class="px-6 py-3">
                Destination
            </th>
            <th scope="col" class="px-6 py-3">
                Gross weight (kg)
            </th>
            <th scope="col" class="px-6 py-3">
                Frieght type
            </th>
            <th scope="col" class="px-6 py-3">
                Status
            </th>
            <th scope="col" class="px-6 py-3">
                Action
            </th>
          </tr>
        </thead>
        <tbody>
          <%= render @quotes %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/quotes/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-2xl">New quote</h1>

  <hr class="mt-3 mb-7" />

  <%= render "form", quote: @quote %>
</div>

app/views/quotes/show.html.erb
<h1 class="font-bold text-2xl"><%= @quote.total_gross_weight %> kg Quote</h1>

<hr class="mt-3 mb-7" />

<div class="flex flex-wrap gap-4 justify-center">
  <%= render "show", quote: @quote %>
</div>

<hr class="mt-7 mb-3" />

<%= link_to "Edit quote", edit_quote_path(@quote), class: "rounded font-medium w-full sm:w-auto px-5 py-2 text-center text-white bg-green-700 inline-block text-sm font-medium" %>

<%= link_to "Back to quotes", quotes_path, class: "rounded font-medium w-full sm:w-auto px-5 py-2 text-center bg-gray-100 inline-block text-sm font-medium" %>