config/routes.rb
# frozen_string_literal: true

# == Route Map
#

Rails.application.routes.draw do
  resources :incoterms, only: %i[index]
  resources :shipments do
    member do
      get :itenary
      get :pdf
    end
  end

  resources :audits, only: %i[destroy]
  resources :quotes do
    member do
      get :pdf
    end
  end
  resources :locations, except: %i[show]
  # resources :customers
  resources :dashboard, only: %i[index]
  get 'dashboard/index'
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :shipments do
        collection do
          post :verify
          get :send_pdf_email
          get :preview_pdf
        end
      end
      resources :quotes, only: %i[create]
      resources :enquiries, only: %i[create]
      resources :incoterms, only: %i[index]
    end
  end

  # Defines the root path route ("/")
  root to: 'shipments#index'
end

app/controllers/api/v1/shipments_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class ShipmentsController < ApiController
      include WickedPdf::PdfHelper

      before_action :set_shipment, only: %i[verify send_pdf preview_pdf]
      before_action :authorize_user!, only: %i[verify send_pdf]

      # GET : /api/v1/shipments
      def show
        shipment = ShippingDetail.includes(:departure, :destination, :incoterm, :location, :receiver, :shipper,
                                           :shipping_information).find(params[:id])
        render_success('success', shipment, ShipmentSerializer)
      end

      # POST : /api/v1/shipments/verify
      def verify
        render_success('success', @shipment, ShipmentSerializer)
      end

      # GET : /api/v1/shipments/send_pdf
      def send_pdf
        missing_params!(:email, :order_number)

        ShipmentMailer.with(shipment: @shipment).new_shipment.deliver_now
        render_success("Order pdf successfully sent to #{params[:email]}")
      end

      # GET : /api/v1/shipments/preview_pdf
      def preview_pdf
        render(template: 'shipments/pdf', pdf: 'shipment', page_size: 'A4', margin: { bottom: 22 }, footer: { html: { template: 'pdf_document_footer' } })
      end

      private

      def set_shipment
        return render_bad_request('Invalid tracking number') unless valid_tracking_number?

        @shipment = ShippingDetail.includes(:departure, :destination, :incoterm, :location, :receiver, :shipper,
                                            :shipping_information).find_by!(tracking_number: params[:order_number])
      end

      def either_recipient_or_sender?
        params[:email].strip.casecmp?(@shipment.shipper.email.strip) || params[:email].strip.casecmp?(@shipment.receiver.email.strip)
      end

      def authorize_user!
        return if either_recipient_or_sender?

        render_unauthorized('The email submitted is not linked with the order')
      end

      def valid_tracking_number?
        return false if params[:order_number].blank?

        params[:order_number].strip!
        params[:order_number] = params[:order_number].scan(/.{1,4}/).join('-') if params[:order_number].count('-').zero? && params[:order_number].length == 12
        params[:order_number].count('-') == 2 && params[:order_number].length <= 14
      end
    end
  end
end

app/controllers/shipments_controller.rb
# frozen_string_literal: true

class ShipmentsController < ApplicationController
  before_action :set_shipment, only: %i[show edit update destroy itenary pdf]

  # GET /shipments or /shipments.json
  def index
    @shipments = ShippingDetail.includes(:location, :receiver, :shipper, :audits, :departure, :destination, :shipping_information).all
  end

  # GET /shipments/1 or /shipments/1.json
  def show; end

  # GET /shipments/1/itenary or /shipments/1/itenary.json
  def itenary
    @audits = @shipment.audits
  end

  # GET /shipments/new
  def new
    @shipment = ShippingDetail.new
    @shipment.build_shipping_information
    @shipment.build_shipper
    @shipment.build_receiver
    @shipment.build_departure
    @shipment.build_destination
    @shipment.build_location
  end

  # GET /shipments/1/edit
  def edit; end

  # GET /shipments/1/pdf
  def pdf
    render_pdf
  end

  # POST /shipments or /shipments.json
  def create
    service = CreateShipmentService.new(params: shipment_params)
    service.perform

    @shipment = service.shipment

    respond_to do |format|
      if service.errors.blank?
        format.html { redirect_to shipment_url(service.shipment), notice: 'Shipment was successfully created.' }
        format.json { render :show, status: :created, location: service.shipment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shipments/1 or /shipments/1.json
  def update
    service = UpdateShipmentService.new(shipment: @shipment, params: shipment_params)
    service.perform

    respond_to do |format|
      if service.errors.blank?
        format.html { redirect_to shipment_url(service.shipment), notice: 'Shipment was successfully updated.' }
        format.json { render :show, status: :ok, location: service.shipment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shipments/1 or /shipments/1.json
  def destroy
    @shipment.destroy

    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove("#{helpers.dom_id(@shipment)}_row") }
      format.html { redirect_to shipments_url, notice: 'Shipment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_shipment
    @shipment = ShippingDetail.includes(:location, :receiver, :shipper, :audits, :departure, :destination, :shipping_information).find(params[:id])
  end

  def shipment_params
    params.require(:shipment).permit(:frieght_type, :height, :length, :width, :description, :status, :weight, :quantity, :dutiable, :declared_value, :incoterm_id, :tracking_number, :incoterm_id, departure_attributes: %i[city country], destination_attributes: %i[city country], shipper_attributes: %i[name email phone], receiver_attributes: %i[name email phone], shipping_information_attributes: %i[company_name address_line1 address_line2], location_attributes: %i[city country])
  end

  def render_pdf
    render(template: 'shipments/pdf', pdf: 'invoice', page_size: 'A4', margin: { bottom: 22 }, footer: { html: { template: 'pdf_document_footer' } })
  end
end

app/helpers/shipments_helper.rb
# frozen_string_literal: true

module ShipmentsHelper
end

app/views/shipments/_shipment.html.erb
<tr id="<%= "#{dom_id(shipment)}_row" %>", class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600" >
  <td scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
      <%= shipment.tracking_number %>
  </td>
  <td class="px-6 py-4">
      <%= shipment.frieght_type&.capitalize %>
  </td>
  <td class="px-6 py-4">
      <%= shipment.departure.city %>
  </td>
  <td class="px-6 py-4">
      <%= shipment.location&.city %>
  </td>
  <td class="px-6 py-4">
      <%= shipment.destination.city %>
  </td>
  <td class="px-6 py-4">
      <%= shipment.status&.gsub("_", " ")&.capitalize %>
  </td>

  <td class="px-6 py-4">
    <%= link_to "Show", shipment_path(shipment), class: "font-medium text-blue-600 dark:text-blue-500 hover:underline" %>
    <%= link_to "Destroy", shipment_path(shipment), data: { turbo_confirm: "Are you sure?", turbo_method: :delete }, class: "font-medium text-red-600 dark:text-red-500 hover:underline" %>
  </td>
</tr>

app/views/shipments/_show.html.erb
<div class="w-full max-w-xl flex-none">
    <dl class="shadow overflow-hidden">
        <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
            <dt class="text-sm font-medium text-blue-600">
                Status
            </dt>
            <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                <%= shipment.status&.tr('_', ' ')&.capitalize %>
            </dd>
        </div>
        <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
            <dt class="text-sm font-medium text-blue-600">
                Location
            </dt>
            <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                <%= shipment.location&.city %>, <%= shipment.location&.country %>
            </dd>
        </div>
        <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
            <dt class="text-sm font-medium text-blue-600">
                Declared value
            </dt>
            <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                <%= ActionController::Base.helpers.number_to_currency(shipment.declared_value, precision: 2) %> USD
            </dd>
        </div>
        <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
            <dt class="text-sm font-medium text-blue-600">
                Date submitted
            </dt>
            <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                <%= shipment.created_at.strftime("%m/%d/%Y, %T") %>
            </dd>
        </div>
        <p class="text-xs font-semibold mb-3 mt-2 px-3">Shipper</p>
        <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
            <dt class="text-sm font-medium text-blue-600">
                Name
            </dt>
            <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                <%= shipment.shipper.name %>
            </dd>
        </div>
        <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
            <dt class="text-sm font-medium text-blue-600">
                Email
            </dt>
            <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                <%= shipment.shipper.email&.downcase || N/A %>
            </dd>
        </div>
        <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
            <dt class="text-sm font-medium text-blue-600">
                Phone
            </dt>
            <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                <%= shipment.shipper.phone.presence || "N/A" %>
            </dd>
        </div>
        <p class="text-xs font-semibold mb-3 mt-2 px-3">Receiver</p>
        <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
            <dt class="text-sm font-medium text-blue-600">
                Name
            </dt>
            <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                <%= shipment.receiver.name %>
            </dd>
        </div>
        <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
            <dt class="text-sm font-medium text-blue-600">
                Email
            </dt>
            <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                <%= shipment.receiver.email&.downcase || N/A %>
            </dd>
        </div>
        <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
            <dt class="text-sm font-medium text-blue-600">
                Phone
            </dt>
            <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                <%= shipment.receiver.phone.presence || "N/A"  %>
            </dd>
        </div>
        <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
            <dt class="text-sm font-medium text-blue-600">
                Address line
            </dt>
            <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                <%= shipment.shipping_information.address_line1 %>
            </dd>
        </div>
    </dl>
</div>

<div class="w-full max-w-xl flex-none">
    <dl class="shadow overflow-hidden">
        <div class="bg-gray-50 px-4 py-3 flex justify-center">
            <%= link_to "History", itenary_shipment_path(@shipment), class: "rounded font-medium px-5 py-2 mx-1 w-full text-center text-dark bg-yellow-500 inline-block text-sm font-medium" %>
            <%= link_to "PDF", pdf_shipment_path(@shipment), class: "rounded font-medium px-5 py-2 mx-1 w-full text-center text-white bg-gray-500 inline-block text-sm font-medium" %>
        </div>
        <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
            <dt class="text-sm font-medium text-blue-600">
                Departure
            </dt>
            <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                <%= shipment.departure.city %>, <%= shipment.departure.country %>
            </dd>
        </div>
        <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
            <dt class="text-sm font-medium text-blue-600">
                Destination
            </dt>
            <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                <%= shipment.destination.city %>, <%= shipment.destination.country %>
            </dd>
        </div>
        <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
            <dt class="text-sm font-medium text-blue-600">
                Frieght
            </dt>
            <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                <%= shipment.frieght_type.capitalize %>
            </dd>
        </div>
        <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
            <dt class="text-sm font-medium text-blue-600">
                Dutiable
            </dt>
            <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                <%= shipment.dutiable? ? "Yes" : "No" %>
            </dd>
        </div>
        <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
            <dt class="text-sm font-medium text-blue-600">
                Dimensions (Ft)
            </dt>
            <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                length: <%= shipment.length %> | width: <%= shipment.width %> | height: <%= shipment.height %>
            </dd>
        </div>
        <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
            <dt class="text-sm font-medium text-blue-600">
                Weight (kg)
            </dt>
            <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                <%= shipment.weight %>
            </dd>
        </div>
        <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
            <dt class="text-sm font-medium text-blue-600">
                Quantity
            </dt>
            <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                <%= shipment.quantity %>
            </dd>
        </div>
        <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
            <dt class="text-sm font-medium text-blue-600">
                Incoterms
            </dt>
            <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                <%= shipment.incoterm.abbr %>
            </dd>
        </div>
        <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
            <dt class="text-sm font-medium text-blue-600">
                Description
            </dt>
            <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                <%= shipment.description %>
            </dd>
        </div>
    </dl>
</div>

app/views/shipments/edit.html.erb
<h1 class="font-bold text-2xl">Editing shipment</h1>

<hr class="mt-3 mb-7" />

<%= render "form", shipment: @shipment %>

app/views/shipments/index.html.erb
<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-2xl">Shipments</h1>
    <%= link_to "New shipment", new_shipment_path, class: "rounded py-2 px-5 bg-blue-600 text-white text-sm block font-medium" %>
  </div>

  <hr class="mt-3 mb-7" />

  <div id="shipments" class="min-w-full">
    <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
      <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
          <tr>
            <th scope="col" class="px-6 py-3">
                Tracking Number
            </th>
            <th scope="col" class="px-6 py-3">
                Frieght type
            </th>
            <th scope="col" class="px-6 py-3">
                Departure
            </th>
            <th scope="col" class="px-6 py-3">
                Location
            </th>
            <th scope="col" class="px-6 py-3">
                Destination
            </th>
            <th scope="col" class="px-6 py-3">
                Status
            </th>
            <th scope="col" class="px-6 py-3">
                Action
            </th>
          </tr>
        </thead>
        <tbody>
            <%= render partial: 'shipment', collection: @shipments %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/shipments/itenary.html.erb
<h1 class="font-bold text-2xl">Itenary <%= @shipment.tracking_number %></h1>

<hr class="mt-3 mb-3" />

<div id="itenary" class="2xl:w-2/3 mx-auto">
  <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
    <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
      <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
          <tr>
              <th scope="col" class="px-6 py-3">
                  Status Date/Time
              </th>
              <th scope="col" class="px-6 py-3">
                  Status
              </th>
              <th scope="col" class="px-6 py-3">
                  Location
              </th>
              <th scope="col" class="px-6 py-3">
                  <span class="sr-only">Delete</span>
              </th>
          </tr>
      </thead>
      <tbody>
            <% @audits.each do |audit| %>
                <tr id="<%= "#{dom_id(audit)}_row" %>", class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
                    <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                        <%= audit.created_at.strftime("%m/%d/%Y %I:%M%p") %>
                    </th>
                    <td class="px-6 py-4">
                        <% if audit.action == 'create' %>
                            <%= ShippingDetail.statuses.key(audit.audited_changes['status']).gsub("_", " ")&.capitalize %>
                        <% else %>
                            <%= ShippingDetail.statuses.key(audit.audited_changes['status']&.last).gsub("_", " ")&.capitalize %>
                        <% end %>
                    </td>
                    <td class="px-6 py-4">
                        <% if audit.action == 'create' %>
                            <%= Location.find_by(id: audit.audited_changes['location_id']).city %>
                        <% else %>
                            <%= Location.find_by(id: audit.audited_changes['location_id'].last.to_i).city %>
                        <% end %>
                    </td>
                    <td class="px-6 py-4 text-right">
                        <%= link_to "Delete", audit_path(audit), data: { turbo_method: :delete }, class: "font-medium text-red-600 dark:text-red-500 hover:underline" %>
                    </td>
                </tr>
            <% end %>
      </tbody>
    </table>
  </div>
</div>

<hr class="mt-3 mb-3" />

<%= link_to "Back to shipment", shipment_path(@shipment), class: "rounded font-medium w-full sm:w-auto px-5 py-2 mb-3 text-center bg-gray-100 inline-block text-sm font-medium" %>

app/views/shipments/new.html.erb
<h1 class="font-bold text-2xl">New shipment</h1>

<hr class="mt-3 mb-7" />

<%= render "form", shipment: @shipment %>

app/views/shipments/pdf.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Invoice</title>
    <style>
        .direction-rtl {
          direction: rtl;
        }
        .header {
          border-collapse: collapse;
          width: 100%;
        }
        .title {
          color: #3fc8a0;
          font-weight: bold;
          font-size: 23px;
        }
        .logo-box {
          display: inline-block;
          width: 800px;
        }
        .logo {
          width: 100%;
          max-width: 50px;
          float: left;
          margin-top: 10px;
        }
        .mrsool-info {
          text-align: right;
          color: #9da3a8;
        }
        .header-box-left {
          text-align: left;
          padding: 10px;
          padding-bottom: 20px;
          border: 2px solid #ebebeb;
          width: 500px;
          float: left;
        }
        .header-box-quote {
          text-align: left;
          padding: 10px;
          padding-bottom: 20px;
          border: 2px solid #ebebeb;
          width: 875px;
          height: 950px;
          float: left;
        }
        .header-box-right {
          text-align: left;
          padding: 10px;
          border: 2px solid #ebebeb;
          width: 500px;
          float: right;
        }
        .header-box-left > div {
          height: 50px;
          margin-bottom: 20px;
        }
        .header-box-right > div {
          height: 50px;
          margin-bottom: 20px;
        }
        .space-box {
          width: 40px;
        }
        .content-table {
          border: 2px solid #ebebeb;
          width: 100%;
          border-collapse: collapse;
          margin-top: 30px;
        }
        .text-right {
          padding-right: 15px;
          font-size: 17px;
          text-align: right;
        }
        .text-left-footer-title {
          padding-left: 15px;
          font-size: 17px;
          text-align: left;
          font-weight: bold;
        }
        .text-right-footer-title {
          padding-right: 15px;
          font-size: 17px;
          text-align: right;
          font-size: 20px;
        }
        .text-left {
          padding-left: 15px;
          font-size: 17px;
          text-align: left;
        }
        .text-right-grey {
          padding-right: 15px;
          text-align: right;
          font-size: 17px;
          color: #9d9d9d;
        }
        .text-left-grey {
          padding-left: 15px;
          text-align: left;
          font-size: 17px;
          color: #9d9d9d;
        }
        .content-table > thead > tr > th {
          background-color: #f2f2f2;
          height: 70px;
        }
        .content-table > tbody > tr {
          border: 2px solid #ebebeb;
          height: 70px;
        }
        .content-table > tfoot > tr {
          background-color: #f2f2f2;
          height: 50px;
        }
        .business-summary .title {
          color: floralwhite;
          text-align: center;
          font-size: 17px;
          background: #00BF6F;
          padding: 8px;
          margin-top: 20px;
        }
        .business-summary span {
          color: #A7A9AC;
        }
        .business-summary table {
          border-radius: 1em;
          overflow: hidden;
          border: none;
        }
        .business-summary table tr {
          height: 57px;
          border: none;
        }
        .business-summary table tr:nth-child(even) {
          background: #F9F9F9;
        }
        .business-summary table tr.sub-total {
          background: #E5F4FF;
          border-bottom: 1px solid #D7DADE;
        }
        .business-summary table tr.sub-total td {
          color: #007CD6;
          font-weight: bold;
        }
        .business-summary table tr.sub-total span {
          color: #49ABF2;
        }
        .business-summary table td {
          color: #000000;
          text-align: center;
        }
        .business-summary table thead tr {
          height: 60px;
        }
        .business-summary table thead th {
          background-color: #F9F9F9;
          color: #000000;
          font-weight: bold;
          font-size: 15px;
        }
        .business-summary table tfoot tr {
          height: 67px;
        }
        .business-summary table tfoot td {
          background-color: #00BF6F;
          color: #FFFFFF;
          font-weight: bold;
          font-size: 20px;
        }
        .business-summary table tfoot span {
          color: #FFFFFF;
        }
        .footer-table {
          border: 2px solid #00BF6F;
          width: 100%;
          border-collapse: collapse;
          margin-top: 30px;
        }
        .footer-table > thead > tr > th {
          padding-right: 15px;
          padding-left: 15px;
          background-color: #00BF6F;
          height: 70px;
          color: white;
        }
        .footer-table > tbody > tr {
          border: 2px solid #00BF6F;
          height: 50px;
        }
        .footer-table > tbody > tr :nth-child(3) {
          color: #00BF6F;
        }
        .footer-grid {
          margin-top: 30px;
          width: 100%;
          border-collapse: collapse;
        }
        .receipt-note-footer-grid {
          margin-top: 110px;
          width: 100%;
          border-collapse: collapse;
        }
        .contract-table {
          direction: rtl;
        }
        .contract-table .tab-col {
          width: 50%;
          vertical-align: top;
        }
        .text-center {
          text-align: center;
        }
        .no-page-break {
          page-break-inside: avoid;
        }
        .page-break {
          display: block;
          clear: both;
          page-break-after: always;
        }
        .contract-detail-table {
          border-collapse: collapse;
          page-break-inside: avoid;
        }
        .contract-detail-table tr {
          border: 1px solid #000000;
        }
        .contract-detail-table tr th {
          border: 1px solid #000000;
          padding: 4px;
        }
        .contract-detail-table tr td {
          text-align: center;
        }
        .contract-detail-table .left-text {
          padding-left: 15px;
          font-size: 17px;
          text-align: left;
        }
        .table-one {
          width: 100%;
        }
        .table-one td {
          padding-top: 8px;
          padding-bottom: 8px;
        }
        .table-two {
          width: 80%;
          margin: 30px auto;
        }
        .contract-footer .dept {
          font-weight: bold;
          color: #154c79;
          margin-bottom: 0px;
        }
        .contract-footer .address {
          margin-top: 0px;
          margin-bottom: 0px;
        }
    </style>
  </head>

  <body onload='number_pages()'>
    <%= render "shipments/EG/pdf_content" %>
    <%= render "shipments/EG/pdf_itenary" %>
  </body>

</html>

app/views/shipments/pdf.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Invoice</title>
    <%= wicked_pdf_stylesheet_link_tag "default_reports" %>
  </head>

  <body onload='number_pages()'>
    <%= render "shipments/EG/pdf_content" %>
    <%= render "shipments/EG/pdf_itenary" %>
  </body>

</html>

app/views/shipments/show.html.erb
<h1 class="font-bold text-2xl">Order #: <%= @shipment.tracking_number %></h1>

<hr class="mt-3 mb-3" />

<div class="flex flex-wrap gap-4 justify-center">
  <%= render partial: 'show', locals: { shipment: @shipment } %>
</div>

<hr class="mt-3 mb-3" />

<%= link_to "Edit shipment", edit_shipment_path(@shipment), class: "rounded font-medium w-full sm:w-auto px-5 py-2 mb-1 text-center text-white bg-green-700 inline-block text-sm font-medium" %>

<%= link_to "Back to shipments", shipments_path, class: "rounded font-medium w-full sm:w-auto px-5 py-2 text-center bg-gray-100 inline-block text-sm font-medium" %>